name: Copilot License Management 
author: Austen Stone
description: Automations to manage copilot licenses. Cleanup inactive, rollouts, reporting.
branding:
  icon: "clock"
  color: "blue"

inputs:
  organization:
    description: The organization to use for the action
    default: ${{ github.repository_owner }}
    required: true
  enterprise:
    description: Search for all organizations in the enterprise (overrides organization) 
    default: null
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  remove:
    description: Whether to remove inactive users
    default: false
    required: false
  remove-from-team:
    description: Whether to remove inactive users from the assigning team
    default: false
    required: false
  inactive-days:
    description: The number of days to consider a user inactive
    default: 90
    required: false
  job-summary:
    description: Whether to output a summary of the job
    default: true
    required: false
  csv:
    description: Whether to output a CSV of the inactive users
    default: false
    required: false
  deploy-users:
    description: Whether to deploy users from a CSV file
    default: false
    required: false
  deploy-users-dry-run:
    description: Whether to do a dry run of deploying users but not actually deploy
    default: true
    required: false
  deploy-users-csv:
    description: CSV file location if deploying users
    default: ./copilot-users.csv
    required: false
  deploy-validation-time:
    description: The number of days to attempt to deploy the user beyond activation date
    default: 3
    required: false

outputs:
  inactive-seats:
    description: JSON array of inactive seats
  inactive-seat-count:
    description: The number of inactive seats
  removed-seats:
    description: The number of seats removed
  seat-count:
    description: The total number of seats
  deployed-seats:
    description: JSON array of deployed seats
  deployed-seat-count:
    description: The number of deployed seats

runs:
  using: "node20"
  main: "dist/index.js"
