name: Notify Inactive Copilot Licenses
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  copilot:
    name: Copilot Seats
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      inactive-logins: ${{ steps.copilot.outputs.inactive-logins }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./
        id: copilot
        with:
          github-token: ${{ secrets.TOKEN }}
          organization: ${{ vars.ORG }}
          inactive-days: 30
          csv: true
  notify-inactive:
    name: Notify Inactive Users
    runs-on: ubuntu-latest
    needs: copilot
    if: needs.copilot.outputs.inactive-logins != '[]'
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        user: ${{ fromJson(needs.copilot.outputs.inactive-logins) }}
    steps:
      - uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: CHANNEL_ID
            text: "Hey <@${{ matrix.user }}>, you have not used Copilot for 30 days. Please contact your manager to free up your seat."