name: Cleanup Copilot Licenses
on:
  push:
    paths:
      - '.github/workflows/usage.yaml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  copilot:
    name: Copilot Seats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.TOKEN }}
          organization: ${{ vars.ORG }}
          inactive-days: 3
          remove: false
          csv: true